### ISSUE TITLE
Ubuntu 15.04 : ImportError: No module named appindicator

### ISSUE THREAD

**Issue by gfelot** [m0sia/pyParrotZik#10]
Hi,

I'm trying your app on U15.04 with a Zic 2.0.

Im getting this : 

'Traceback (most recent call last):
  File "./ParrotZikTray", line 173, in <module>
    indicator = ParrotZikIndicator()
  File "./ParrotZikTray", line 45, in __init__
    SysIndicator.__init__(self,icon = "zik-audio-headset",menu = self.menu)
  File "/home/ragnar/Epitech/pyParrotZik-master/SysIndicator.py", line 22, in __init__
    import appindicator
ImportError: No module named appindicator'

Any idea ?

Thanks for the work...

**Comment by m0sia** [comment]
Hi,

You have to install python-appindicator

$sudo apt-get install python-appindicator

Thanks,
Dima

**Comment by RagnarLodbrok** [comment]
Thanks I missed that ;)

**Comment by RagnarLodbrok** [comment]
Now I can lauch it.

I connect my Zic v2 with BT like Im used to do. But the application stay in unconnected mode.
Any idea ?

**Comment by m0sia** [comment]
Zik2.0 support added in #12
