### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by bartoszkopinski** [m0sia/pyParrotZik#2]
Hi,
Nice job here, how did you manage to reverse engineer the firmware?

Anyway, I was able to run the script under OSX 10.9 with [some small changes](https://github.com/bartoszkopinski/pyParrotZik/commit/c280063b1301410bc81b8434fadec82c598c7554) but I stuck on:

``` python
Connecting to "Parrot RFcomm service" on 90:03:B7:5E:BE:30
Traceback (most recent call last):
  File "./ParrotZikTrayMac", line 213, in <module>
    if indicator.EstablishConnection():
  File "./ParrotZikTrayMac", line 77, in EstablishConnection
    self.parrot = ParrotZik.ParrotZik(mac)
  File "/Users/bartek/python/pyParrotZik/ParrotZik.py", line 50, in __init__
    self.sock.send('\x00\x03\x00')
  File "/Library/Python/2.7/site-packages/lightblue/_bluetoothsockets.py", line 530, in send
    raise _socket.error(result, "Error sending data")
socket.error: [Errno -536870208] Error sending data
```

Any ideas on this?

I've seen some OSX support commits, but did you get to have it working under OSX? If so, what are your firmware and lightblue versions?

Cheers,
Bartosz

**Comment by m0sia** [comment]
No plans to implement Mac version as soon native implementation from @vincent-le-normand is available.
