### ISSUE TITLE
sudo required to run

### ISSUE THREAD

**Issue by charlesbakervt** [m0sia/pyParrotZik#5]
First of all, I wanted to say this app is awesome. Being able to use my headphones properly with Ubuntu is something I have wanted ever since I bought my headphones.

Now, I skimmed through the code for a while to figure out why I wasn't working at first until I finally realized I needed to run it with:

    sudo ./ParrotZikTray

Is there is a way to make the code run without requiring sudo privileges? Alternatively, do you have an idea of what part of the code requires sudo? If so, do you know of a way that I could change privileges of that required component so that it no longer needs sudo?

Thanks again.

**Comment by m0sia** [comment]
Can't reproduce with the latest changes
