### ISSUE TITLE
sh: bluez-test-device: command not found

### ISSUE THREAD

**Issue by Fogelholk** [m0sia/pyParrotZik#7]
Hi!

I'm current running OpenSUSE (Tumbleweed) with KDE but I am unable to start this nifty little tool. I've installed most packages needed for it to start, including [python-pybluez](http://software.opensuse.org/package/python-pybluez) and [python-appindicator](http://software.opensuse.org/package/python-appindicator) (from the MATE repository!) but I've finally hit a stop being unable to find which package is missing that would fit the needs to start this program with the message:

> sh: bluez-test-device: command not found

I'm not a Python programmer, so any help would be awesome!

**Comment by m0sia** [comment]
Can you try the latest version?
