### ISSUE TITLE
Zik2

### ISSUE THREAD

**Issue by antoine-lemasson** [m0sia/pyParrotZik#8]
Hi, 
I managed to get pyParrotZik working for Parrot Zik2 headset.
I was wondering how did you managedt to get proper querry path. ( like /api/audio/noise_cancellation/enabled/get ) as they are not documented anywhere.
As you may be aware, the zik2 give acces to more options and I was wondering if I could incorporate those options in the pyParrotZik.
I will fork pyParrot in my account and submit my changes for Parrot Zik2.
Cheers,
Antoine

**Comment by m0sia** [comment]
Hi Antoine!

There are two ways to find paths:
- Android Parrot Zik application
- Parrot Zik firmware

Both are very easy to reverse. This is the paths for parrot zik 2.0. 

```
$ strings zik_release_2.04.plf | grep '/api'
/api/audio/track/metadata/get
/api
/api/audio/noise_control/enabled/get
/api/audio/noise_control/enabled/set?arg
/api/audio/noise_control/get
/api/audio/noise_control/set?arg
/api/audio/noise_control/phone_mode/get
/api/audio/noise_control/phone_mode/set?arg
/api/audio/noise_cancellation/enabled/get
/api/audio/noise_cancellation/enabled/set?arg
/api/audio/thumb_equalizer/value/set?arg
/api/audio/thumb_equalizer/value/get
/api/audio/equalizer/enabled/get
/api/audio/equalizer/enabled/set?arg
/api/audio/param_equalizer/value/set?arg
/api/audio/smart_audio_tune/set?arg
/api/audio/smart_audio_tune/get
/api/audio/preset/bypass/set?arg
/api/audio/preset/bypass/get
/api/audio/preset/download?name
/api/audio/preset/activate?id
/api/audio/preset/save?name
/api/audio/preset/remove?id
/api/audio/preset/counter/get
/api/audio/preset/clear_all
/api/audio/preset/synchro/start
/api/audio/preset/synchro/stop
/api/audio/preset/current/get
/api/audio/preset/cancel_producer
/api/audio/sound_effect/enabled/get
/api/audio/sound_effect/enabled/set?arg
/api/audio/sound_effect/angle/get
/api/audio/sound_effect/angle/set?arg
/api/audio/sound_effect/room_size/get
/api/audio/sound_effect/room_size/set?arg
/api/audio/sound_effect/get
/api/audio/noise/get
/api/software/version/get
/api/software/version_checking/get
/api/bluetooth/friendlyname/get
/api/bluetooth/friendlyname/set?arg
/api/software/download_size/set?arg
/api/software/download_check_state/get
/api/system/battery/forecast/get
/api/system/battery/get
/api/audio/track/metadata/get
/api/audio/track/metadata/force?artist
/api/audio/source/get
/api/system/auto_connection/enabled/get
/api/system/auto_connection/enabled/set?arg
/api/system/factory_reset
/api/system/anc_phone_mode/enabled/get
/api/system/anc_phone_mode/enabled/set?arg
/api/system/device_type/get
/api/system/color/get
/api/system/pi/get
/api/system/auto_power_off/presets_list/get
/api/system/auto_power_off/get
/api/system/auto_power_off/set?arg
/api/system/head_detection/enabled/get
/api/system/head_detection/enabled/set?arg
/api/audio/specific_mode/enabled/get
/api/audio/specific_mode/enabled/set?arg
/api/system/bt_address/get
/api/appli_version/set?arg
/api/system/calibrate
/api/account/username/get
/api/account/username/set?arg
/api/audio/equalizer/preset_id/set?arg
/api/audio/equalizer/preset_value/set?arg
/api/software/tts/enable
/api/software/tts/disable
/api/software/tts/get
/api/flight_mode/enable
/api/flight_mode/disable
/api/flight_mode/get
```

It will be great if you can push your modifications back to my source base.

**Comment by antoine-lemasson** [comment]
Great i will most most likely make the modifications
and some updates during the week and push
There are some slight differences, maybe a second
branch for zik2.0 can be made.

Cheers,
Antoine.

**Comment by RagnarLodbrok** [comment]
Any progress on the Zic 2.0 ???

**Comment by m0sia** [comment]
Hi,

Generally Zik2.0 should work.
What functions of 2.0 are you looking for to add? 

 I can add some features and you can test it out. I don't own Zik2.0 to test by myself.

Thanks,
Dima

**Comment by antoine-lemasson** [comment]
I have just push to my repos my updates on this.  [https://github.com/antoine-lemasson/pyParrotZik2]
This is operational, even though much more work may be needed 
What is working and tested on my zik2.0: 
- Noise cancellation
- Select Mode (COncert Hall, Jazz, Living Room, Silent room)
- Flight mode
- Toggle auto connection
What is not working did not find ime to work it out: 
- Equalizer 

I have no time to finalize this but work is needed to merge with pyParrotZik and toggle on/off option depending on the device connected
Cheers,
Antoine

**Comment by RagnarLodbrok** [comment]
Merci antoine. Dev en python ? Je dois m'y mettre ;)

**Comment by antoine-lemasson** [comment]
Non, mon fond de commerce c'est plutot le c++,
mais on va dire curiosité et loisir !
A+

**Comment by serathius** [comment]
Most advanced implementation yet: https://github.com/serathius/pyParrotZik
Tested on ubuntu 15.04
Post problems here: https://github.com/m0sia/pyParrotZik/pull/12

**Comment by m0sia** [comment]
Merged changes from @serathius
